### PR TITLE
Issue #56380: Remove community page & link to it.

### PR DESCRIPTION
**Pull request by anotherjames**
For https://support.computerminds.co.uk/issues/56380 .

I believe I used to have direct access as a contributor to this repo (see my previous commits & PRs - e.g. https://github.com/Activiti/activiti.github.io/pull/22), but apparently no longer, so I've had to go via a fork.

### CODE REVIEW

**Comment by anotherjames** [comment]
Hi @erdemedeiros and @mteodori - I've been asked to request a review for this from you, but I don't have access to even set the reviewer on this PR?

**Comment by mteodori** [comment]
@anotherjames I can approve and merge and add you back as contributor but we use PR for everything anyway, I don't get what this issue is about as it references an issue tracker I cannot access and this readme page is not linked from the root

**Comment by anotherjames** [comment]
Sorry, sure. @jsantos-alfresco requested that we do this work, and that is our usual process on projects. For posterity, this was the ticket's contents:

### Remove community page

Hello, we want to remove the following page all together: https://www.activiti.org/community 
[...]
We have decided to remove the sentence from the readme that references this page, and then remove the page completely, thanks.

---

So - @jsantos-alfresco (and @mteodori) - what's the best way to track issues/work going forward? I suggest perhaps raising issues here instead of on our redmine there. Where did the issue originate from before reaching us? Perhaps that discussion could be had here to help us all rather than starting on our private issue tracker.

**Comment by jsantos-alfresco** [comment]
Hello @mteodori, the request came from Ian Norton and the web team. We used to be able to make changes directly to the repo, but I see that is no longer the case. That page displays an empty calendar which is misleading to the user so I was asked to remove it, together with any reference to the page.

Next time I will create a PR here directly.

**Pull request merged**
