### PR TITLE
WIP: Copy alfresco.com cookie banner

### PR DESCRIPTION
**Pull request by stevetweeddale**
I'm off this next week, so leaving this here in case @anotherjames needs to pick it up.

Todo:
- Finish the styling. So far I've got it mostly looking right just by copying the css from the main site and tweaking it to account for base style differences. The main thing we're still missing is the Museo Slab font from the main Alfresco website. Will want to check if we think it's worth including a whole webfont just for this cookie banner. If not, we'll need to tweak font sizes and whatnot for the headings and buttons just for this site.
- Add javascript to do 2 things:
  - Hide it, then jQuery slide the banner in from the top on page load if the cookie isn't set.
  - Set a cookie and slide the thing away when hitting OK.

### CODE REVIEW

**Comment by Salaboy** [comment]
@stevetweeddale @anotherjames hi guys.. can you please let me know who is going to merge this PRs?

**Comment by anotherjames** [comment]
Hi @Salaboy the work needs completing first. I'll take it on today in Steve's absence.

**Comment by inavarre** [comment]
Hi @anotherjames  That's right this pull request is for: https://support.computerminds.co.uk/issues/48381#change-290928

@Salaboy Once James finishes this off we need to run it through QA and then we can get it on the site. Myself of ComputerMinds will merge.

**Comment by anotherjames** [comment]
@inavarre @Salaboy as Steve mentioned above, one of the outstanding parts to do is about the font to use in the banner. Do you want the Museo Slab font included, just for the banner? I would have thought that it would be unnecessary, but I'll let you make that call.

**Comment by inavarre** [comment]
I've changed the link colour to the cookie banner links. Happy for this to get merged to master.

**Comment by anotherjames** [comment]
Merge conflicts resolved... and merged to master!

**Pull request merged**
